name: alicom
description: "Alicom e-commerce application"

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7+1
  flutter_screenutil: ^5.9.3
  equatable: ^2.0.7
  geocoding: ^3.0.0
  geolocator: ^13.0.4
  dio: ^5.8.0+1
  get_it: ^8.0.3
  shimmer: ^3.0.0
  flutter_svg_provider: ^1.0.7
  flutter_svg: ^2.0.17
  lottie: ^3.3.1
  path_provider: ^2.1.5
  flash: ^3.1.1
  image_picker: ^1.1.2
  pin_code_fields: ^8.0.1
  flutter_rating_bar: ^4.0.1
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  url_launcher: ^6.3.1
  share_plus: ^10.1.4
  package_info_plus: ^8.3.0
  flutter_widget_from_html: ^0.16.0
  flutter_dotenv: ^5.2.1
  encrypt: ^5.0.3
  build_runner: ^2.4.15
  flutter_spinkit: ^5.2.1
  croppy: ^1.3.6
  dartz: ^0.10.1
  carousel_slider: ^5.0.0
  flutter_staggered_grid_view: ^0.7.0
  internet_connection_checker_plus: ^2.7.1
  shared_preferences: ^2.5.3
  flutter_gen_runner: ^5.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash:


  flutter_lints: ^5.0.0

flutter_gen:
  output: lib/gen
  line_length: 50

  integrations:
    flutter_svg: true
    lottie: true

  assets:
    enabled: true

    outputs:
      class_name: MyAssets

  fonts:
    enabled: true
    outputs:
      class_name: MyFontFamily

flutter:


  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/lang/

  fonts:
    - family: Black
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
    - family: ExtraBold
      fonts:
        - asset: assets/fonts/Cairo-ExtraBold.ttf
    - family: CairoBold
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
    - family: CairoRegular
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: CairoSemiBold
      fonts:
        - asset: assets/fonts/Cairo-SemiBold.ttf


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

# تكوين شاشة البداية
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icons/icon.png"
  android_12:
    image: "assets/icons/icon.png"
    icon_background_color: "#FFFFFF"
  fullscreen: true
  android: true
  ios: true
  web: false
  branding: "assets/icons/icon.png"
  image_dark: "assets/icons/icon.png"
  color_dark: "#FFFFFF"